apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealsdeals-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dealsdeals
  template:
    metadata:
      labels:
        app: dealsdeals
    spec:
      containers:
      - name: dealsdeals
        image: pooyanazad/dealsdeals:v1.01
        ports:
        - containerPort: 5000
